stages:
  - build

.node_template:
  image: node:12
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    paths:
    - .npm/

lint-test-build:
  extends: .node_template
  stage: build
  script:
   - npm run lint
   - npm run test
   - npm run build:prod
  artifacts:
    paths:
      - dist/
